import { motion, AnimatePresence } from 'motion/react';
import { X, AlertCircle, Shield, FileText } from 'lucide-react';

export type LegalDocumentType = 'disclaimer' | 'privacy' | 'terms' | null;

interface LegalModalProps {
  type: LegalDocumentType;
  onClose: () => void;
  lang: 'fr' | 'en';
}

export function LegalModal({ type, onClose, lang }: LegalModalProps) {
  if (!type) return null;

  const content = {
    disclaimer: {
      icon: <AlertCircle className="w-6 h-6" />,
      color: "text-amber-600 bg-amber-100",
      title: lang === 'fr' ? "Clause d'exclusion de garantie et de résultats" : "Disclaimer",
      sections: lang === 'fr' ? [
        { t: "1. Absence de garantie de résultats", p: "L'application Asphaltvision est fournie à des fins d'information / de divertissement / de service. L'utilisateur reconnaît expressément que l'utilisation de l'application et de ses fonctionnalités ne garantit aucun résultat spécifique, financier, professionnel ou autre." },
        { t: "2. Nature des prédictions ou suggestions", p: "Toute donnée, suggestion, analyse ou \"vision\" générée par l'application est fournie à titre indicatif uniquement. Ces éléments ne doivent en aucun cas être interprétés comme des conseils professionnels ou des certitudes. L'éditeur ne garantit pas l'exactitude, la fiabilité ou l'exhaustivité des résultats obtenus via l'application." },
        { t: "3. Risques liés à l'utilisateur", p: "L'utilisateur assume l'entière responsabilité de toute décision prise sur la base des informations fournies par l'application. L'éditeur décline toute responsabilité pour toute perte, dommage ou préjudice (direct ou indirect) découlant d'une interprétation ou d'une utilisation des résultats de l'application." }
      ] : [
        { t: "1. No Guarantee of Results", p: "The Asphaltvision application is provided for informational, entertainment, or service purposes. The user expressly acknowledges that the use of the application and its features does not guarantee any specific financial, professional, or other results." },
        { t: "2. Nature of Predictions or Suggestions", p: "Any data, suggestion, analysis, or \"vision\" generated by the application is provided for guidance purposes only. These elements must in no case be interpreted as professional advice or certainties. The publisher does not guarantee the accuracy, reliability, or completeness of the results obtained through the application." },
        { t: "3. Risks Borne by the User", p: "The user assumes full responsibility for any decision made based on the information provided by the application. The publisher disclaims all responsibility for any loss, damage, or harm (direct or indirect) resulting from an interpretation or use of the application's results." }
      ]
    },
    privacy: {
      icon: <Shield className="w-6 h-6" />,
      color: "text-blue-600 bg-blue-100",
      title: lang === 'fr' ? "Politique de Confidentialité" : "Privacy Policy",
      sections: lang === 'fr' ? [
        { t: "1. Collecte des données", p: "Nous collectons uniquement les images que vous soumettez volontairement pour utiliser notre outil de simulation de scellant d'asphalte." },
        { t: "2. Traitement par l'IA", p: "Les images soumises sont traitées de façon sécuritaire par l'intermédiaire de services d'intelligence artificielle. Nous ne vendons, ne louons, ni ne partageons vos photos avec des tiers à des fins publicitaires." },
        { t: "3. Stockage et Sécurité", p: "Nous mettons en œuvre des mesures de sécurité pour protéger vos informations. Les images téléchargées ne sont stockées temporairement que le temps nécessaire au traitement." }
      ] : [
        { t: "1. Data Collection", p: "We only collect images that you voluntarily submit to use our asphalt sealant simulation tool." },
        { t: "2. AI Processing", p: "Submitted images are processed securely through artificial intelligence services. We do not sell, rent, or share your photos with third parties for advertising purposes." },
        { t: "3. Storage and Security", p: "We implement security measures to protect your information. Uploaded images are only temporarily stored for the time needed for processing." }
      ]
    },
    terms: {
      icon: <FileText className="w-6 h-6" />,
      color: "text-emerald-600 bg-emerald-100",
      title: lang === 'fr' ? "Conditions d'Utilisation" : "Terms of Use",
      sections: lang === 'fr' ? [
        { t: "1. Acceptation", p: "En utilisant l'application AsphaltVision, vous acceptez de vous conformer à ces conditions d'utilisation." },
        { t: "2. Utilisation permise", p: "Ce service vous permet de visualiser des rendus d'asphalte simulés. Vous vous engagez à ne pas utiliser l'application de manière abusive, illégale ou pour perturber le bon fonctionnement du service." },
        { t: "3. Propriété", p: "L'interface de l'application, la marque AsphaltVision et le code original sont la propriété de l'éditeur. Les images générées vous sont fournies pour usage personnel et évaluation." }
      ] : [
        { t: "1. Acceptance", p: "By using the AsphaltVision application, you agree to comply with these terms of use." },
        { t: "2. Permitted Use", p: "This service allows you to view simulated asphalt renders. You agree not to misuse the application, use it illegally, or disrupt the proper functioning of the service." },
        { t: "3. Property", p: "The application interface, the AsphaltVision brand, and the original code are the property of the publisher. Generated images are provided to you for personal use and evaluation." }
      ]
    }
  };

  const doc = content[type];

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
        className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50"
      />
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 pointer-events-none">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="bg-white rounded-3xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col pointer-events-auto border border-zinc-200"
        >
          {/* Header */}
          <div className="flex items-center justify-between p-6 border-b border-zinc-100 shrink-0">
            <div className="flex items-center space-x-3">
              <div className={`${doc.color} p-2 rounded-xl`}>
                {doc.icon}
              </div>
              <h2 className="text-xl font-bold font-display text-zinc-900">
                {doc.title}
              </h2>
            </div>
            <button
              onClick={onClose}
              className="p-2 text-zinc-400 hover:text-zinc-600 hover:bg-zinc-100 rounded-full transition-colors"
              aria-label="Fermer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Content */}
          <div className="p-6 md:p-8 overflow-y-auto w-full max-w-none space-y-6 text-zinc-600">
            {doc.sections.map((section, idx) => (
              <div key={idx} className="space-y-2">
                <h3 className="font-bold text-zinc-900 text-lg">{section.t}</h3>
                <p className="leading-relaxed text-sm">
                  {section.p}
                </p>
              </div>
            ))}
          </div>

          {/* Footer */}
          <div className="p-6 border-t border-zinc-100 flex justify-end shrink-0">
            <button
              onClick={onClose}
              className="px-6 py-2.5 bg-emerald-600 text-white rounded-xl font-bold hover:bg-emerald-700 transition-colors active:scale-95"
            >
              {lang === 'fr' ? 'Compris' : 'Understood'}
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
